import xlsxwriter
import os
import datetime

print("\nWelcome to the GHG Emissions DataGen Tool!\nThis can be used to generate .xlsx files that when accessed through a Microsoft Excel session with a Bloomberg Terminal plugin, will output the company's most recent GHG emissions data.\n")
tickers = input("Enter the ticker, then an underscore, then the Bloomberg exchange country code for your desired company. For example for Microsoft you would enter MSFT_US. If you want to generate the template sheets for multiple companies use a '+' to separate them like this: XOM_US+CNQ_CN+SU_CN.\n\n")
tickers = tickers.upper().replace("_", " ").split("+")

directory = str(int(datetime.datetime.now().timestamp()))

if not os.path.exists(directory):
    os.makedirs(directory)

for ticker in tickers:
    try:
        workbook = xlsxwriter.Workbook(directory + '/GHG_Emissions_' + ticker.replace("/","-") + '.xlsx')
        worksheet = workbook.add_worksheet()

        worksheet.write('A1', ticker + " 2023")
        worksheet.write('B1', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_1", "FY 2023")')
        worksheet.write('C1', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_2_LOCATION_BASED", "FY 2023")')
        worksheet.write('D1', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_3", "FY 2023")')
        worksheet.write('E1', '=BDH("' + ticker + ' Equity", "SCOPE_3_PURCH_GOODS_SRVCS", "FY 2023")')
        worksheet.write('F1', '=BDH("' + ticker + ' Equity", "SCOPE_3_CAPITAL_GOODS", "FY 2023")')
        worksheet.write('G1', '=BDH("' + ticker + ' Equity", "SCOPE_3_FUEL_ENRG_RELATD_ACT", "FY 2023")')
        worksheet.write('H1', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_TRANS_DIST", "FY 2023")')
        worksheet.write('I1', '=BDH("' + ticker + ' Equity", "SCOPE_3_WASTE_GENRTD_IN_OP", "FY 2023")')
        worksheet.write('J1', '=BDH("' + ticker + ' Equity", "SCOPE_3_BUSINESS_TRVL_EMISSIONS", "FY 2023")')
        worksheet.write('K1', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMPLOYEE_COMMUTING", "FY 2023")')
        worksheet.write('L1', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_LEASED_ASSETS", "FY 2023")')
        worksheet.write('M1', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_TRANS_DIST", "FY 2023")')
        worksheet.write('N1', '=BDH("' + ticker + ' Equity", "SCOPE_3_PRCSS_OF_SOLD_PRODS", "FY 2023")')
        worksheet.write('O1', '=BDH("' + ticker + ' Equity", "SCOPE_3_USE_SOLD_PRODUCTS", "FY 2023")')
        worksheet.write('P1', '=BDH("' + ticker + ' Equity", "SCOPE_3_EOL_TRTMNT_PRODS", "FY 2023")')
        worksheet.write('Q1', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_LEASE_ASSTS", "FY 2023")')
        worksheet.write('R1', '=BDH("' + ticker + ' Equity", "SCOPE_3_FRANCHISES", "FY 2023")')
        worksheet.write('S1', '=BDH("' + ticker + ' Equity", "SCOPE_3_INVESTMENTS", "FY 2023")')
        worksheet.write('T1', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMISSIONS_OTHER", "FY 2023")')
        worksheet.write('U1', '=BDH("' + ticker + ' Equity", "ENTERPRISE_VALUE", "FY 2023")')
        worksheet.write('V1', '=BDH("' + ticker + ' Equity", "IS_COMP_SALES", "FY 2023")')
        worksheet.write('W1', '=BDH("' + ticker + ' Equity", "HISTORICAL_MARKET_CAP", "FY 2023")')
        worksheet.write('X1', '=BDP("' + ticker + ' Equity", "NAME")')
        worksheet.write('Y1', '=BDH("' + ticker + ' Equity", "IS_AVG_NUM_SH_FOR_EPS", "FY 2023")')
        worksheet.write('Z1', '=BDH("' + ticker + ' Equity", "PX_LAST", "FY 2023")')
        worksheet.write('AA1', '=BDH("' + ticker + ' Equity", "SHORT_AND_LONG_TERM_DEBT", "FY 2023")')
        worksheet.write('AB1', '=BDH("' + ticker + ' Equity", "CASH_AND_MARKETABLE_SECURITIES", "FY 2023")')
        worksheet.write('AC1', '=BDH("' + ticker + ' Equity", "BS_TOT_ASSET", "FY 2023")')

        worksheet.write('A2', ticker + " 2022")
        worksheet.write('B2', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_1", "FY 2022")')
        worksheet.write('C2', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_2_LOCATION_BASED", "FY 2022")')
        worksheet.write('D2', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_3", "FY 2022")')
        worksheet.write('E2', '=BDH("' + ticker + ' Equity", "SCOPE_3_PURCH_GOODS_SRVCS", "FY 2022")')
        worksheet.write('F2', '=BDH("' + ticker + ' Equity", "SCOPE_3_CAPITAL_GOODS", "FY 2022")')
        worksheet.write('G2', '=BDH("' + ticker + ' Equity", "SCOPE_3_FUEL_ENRG_RELATD_ACT", "FY 2022")')
        worksheet.write('H2', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_TRANS_DIST", "FY 2022")')
        worksheet.write('I2', '=BDH("' + ticker + ' Equity", "SCOPE_3_WASTE_GENRTD_IN_OP", "FY 2022")')
        worksheet.write('J2', '=BDH("' + ticker + ' Equity", "SCOPE_3_BUSINESS_TRVL_EMISSIONS", "FY 2022")')
        worksheet.write('K2', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMPLOYEE_COMMUTING", "FY 2022")')
        worksheet.write('L2', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_LEASED_ASSETS", "FY 2022")')
        worksheet.write('M2', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_TRANS_DIST", "FY 2022")')
        worksheet.write('N2', '=BDH("' + ticker + ' Equity", "SCOPE_3_PRCSS_OF_SOLD_PRODS", "FY 2022")')
        worksheet.write('O2', '=BDH("' + ticker + ' Equity", "SCOPE_3_USE_SOLD_PRODUCTS", "FY 2022")')
        worksheet.write('P2', '=BDH("' + ticker + ' Equity", "SCOPE_3_EOL_TRTMNT_PRODS", "FY 2022")')
        worksheet.write('Q2', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_LEASE_ASSTS", "FY 2022")')
        worksheet.write('R2', '=BDH("' + ticker + ' Equity", "SCOPE_3_FRANCHISES", "FY 2022")')
        worksheet.write('S2', '=BDH("' + ticker + ' Equity", "SCOPE_3_INVESTMENTS", "FY 2022")')
        worksheet.write('T2', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMISSIONS_OTHER", "FY 2022")')
        worksheet.write('U2', '=BDH("' + ticker + ' Equity", "ENTERPRISE_VALUE", "FY 2022")')
        worksheet.write('V2', '=BDH("' + ticker + ' Equity", "IS_COMP_SALES", "FY 2022")')
        worksheet.write('W2', '=BDH("' + ticker + ' Equity", "HISTORICAL_MARKET_CAP", "FY 2022")')
        worksheet.write('X2', '=BDP("' + ticker + ' Equity", "NAME")')
        worksheet.write('Y2', '=BDH("' + ticker + ' Equity", "IS_AVG_NUM_SH_FOR_EPS", "FY 2022")')
        worksheet.write('Z2', '=BDH("' + ticker + ' Equity", "PX_LAST", "FY 2022")')
        worksheet.write('AA2', '=BDH("' + ticker + ' Equity", "SHORT_AND_LONG_TERM_DEBT", "FY 2022")')
        worksheet.write('AB2', '=BDH("' + ticker + ' Equity", "CASH_AND_MARKETABLE_SECURITIES", "FY 2022")')
        worksheet.write('AC2', '=BDH("' + ticker + ' Equity", "BS_TOT_ASSET", "FY 2022")')

        worksheet.write('A3', ticker + " 2021")
        worksheet.write('B3', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_1", "FY 2021")')
        worksheet.write('C3', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_2_LOCATION_BASED", "FY 2021")')
        worksheet.write('D3', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_3", "FY 2021")')
        worksheet.write('E3', '=BDH("' + ticker + ' Equity", "SCOPE_3_PURCH_GOODS_SRVCS", "FY 2021")')
        worksheet.write('F3', '=BDH("' + ticker + ' Equity", "SCOPE_3_CAPITAL_GOODS", "FY 2021")')
        worksheet.write('G3', '=BDH("' + ticker + ' Equity", "SCOPE_3_FUEL_ENRG_RELATD_ACT", "FY 2021")')
        worksheet.write('H3', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_TRANS_DIST", "FY 2021")')
        worksheet.write('I3', '=BDH("' + ticker + ' Equity", "SCOPE_3_WASTE_GENRTD_IN_OP", "FY 2021")')
        worksheet.write('J3', '=BDH("' + ticker + ' Equity", "SCOPE_3_BUSINESS_TRVL_EMISSIONS", "FY 2021")')
        worksheet.write('K3', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMPLOYEE_COMMUTING", "FY 2021")')
        worksheet.write('L3', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_LEASED_ASSETS", "FY 2021")')
        worksheet.write('M3', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_TRANS_DIST", "FY 2021")')
        worksheet.write('N3', '=BDH("' + ticker + ' Equity", "SCOPE_3_PRCSS_OF_SOLD_PRODS", "FY 2021")')
        worksheet.write('O3', '=BDH("' + ticker + ' Equity", "SCOPE_3_USE_SOLD_PRODUCTS", "FY 2021")')
        worksheet.write('P3', '=BDH("' + ticker + ' Equity", "SCOPE_3_EOL_TRTMNT_PRODS", "FY 2021")')
        worksheet.write('Q3', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_LEASE_ASSTS", "FY 2021")')
        worksheet.write('R3', '=BDH("' + ticker + ' Equity", "SCOPE_3_FRANCHISES", "FY 2021")')
        worksheet.write('S3', '=BDH("' + ticker + ' Equity", "SCOPE_3_INVESTMENTS", "FY 2021")')
        worksheet.write('T3', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMISSIONS_OTHER", "FY 2021")')
        worksheet.write('U3', '=BDH("' + ticker + ' Equity", "ENTERPRISE_VALUE", "FY 2021")')
        worksheet.write('V3', '=BDH("' + ticker + ' Equity", "IS_COMP_SALES", "FY 2021")')
        worksheet.write('W3', '=BDH("' + ticker + ' Equity", "HISTORICAL_MARKET_CAP", "FY 2021")')
        worksheet.write('X3', '=BDP("' + ticker + ' Equity", "NAME")')
        worksheet.write('Y3', '=BDH("' + ticker + ' Equity", "IS_AVG_NUM_SH_FOR_EPS", "FY 2021")')
        worksheet.write('Z3', '=BDH("' + ticker + ' Equity", "PX_LAST", "FY 2021")')
        worksheet.write('AA3', '=BDH("' + ticker + ' Equity", "SHORT_AND_LONG_TERM_DEBT", "FY 2021")')
        worksheet.write('AB3', '=BDH("' + ticker + ' Equity", "CASH_AND_MARKETABLE_SECURITIES", "FY 2021")')
        worksheet.write('AC3', '=BDH("' + ticker + ' Equity", "BS_TOT_ASSET", "FY 2021")')

        worksheet.write('A4', ticker + " 2020")
        worksheet.write('B4', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_1", "FY 2020")')
        worksheet.write('C4', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_2_LOCATION_BASED", "FY 2020")')
        worksheet.write('D4', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_3", "FY 2020")')
        worksheet.write('E4', '=BDH("' + ticker + ' Equity", "SCOPE_3_PURCH_GOODS_SRVCS", "FY 2020")')
        worksheet.write('F4', '=BDH("' + ticker + ' Equity", "SCOPE_3_CAPITAL_GOODS", "FY 2020")')
        worksheet.write('G4', '=BDH("' + ticker + ' Equity", "SCOPE_3_FUEL_ENRG_RELATD_ACT", "FY 2020")')
        worksheet.write('H4', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_TRANS_DIST", "FY 2020")')
        worksheet.write('I4', '=BDH("' + ticker + ' Equity", "SCOPE_3_WASTE_GENRTD_IN_OP", "FY 2020")')
        worksheet.write('J4', '=BDH("' + ticker + ' Equity", "SCOPE_3_BUSINESS_TRVL_EMISSIONS", "FY 2020")')
        worksheet.write('K4', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMPLOYEE_COMMUTING", "FY 2020")')
        worksheet.write('L4', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_LEASED_ASSETS", "FY 2020")')
        worksheet.write('M4', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_TRANS_DIST", "FY 2020")')
        worksheet.write('N4', '=BDH("' + ticker + ' Equity", "SCOPE_3_PRCSS_OF_SOLD_PRODS", "FY 2020")')
        worksheet.write('O4', '=BDH("' + ticker + ' Equity", "SCOPE_3_USE_SOLD_PRODUCTS", "FY 2020")')
        worksheet.write('P4', '=BDH("' + ticker + ' Equity", "SCOPE_3_EOL_TRTMNT_PRODS", "FY 2020")')
        worksheet.write('Q4', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_LEASE_ASSTS", "FY 2020")')
        worksheet.write('R4', '=BDH("' + ticker + ' Equity", "SCOPE_3_FRANCHISES", "FY 2020")')
        worksheet.write('S4', '=BDH("' + ticker + ' Equity", "SCOPE_3_INVESTMENTS", "FY 2020")')
        worksheet.write('T4', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMISSIONS_OTHER", "FY 2020")')
        worksheet.write('U4', '=BDH("' + ticker + ' Equity", "ENTERPRISE_VALUE", "FY 2020")')
        worksheet.write('V4', '=BDH("' + ticker + ' Equity", "IS_COMP_SALES", "FY 2020")')
        worksheet.write('W4', '=BDH("' + ticker + ' Equity", "HISTORICAL_MARKET_CAP", "FY 2020")')
        worksheet.write('X4', '=BDP("' + ticker + ' Equity", "NAME")')
        worksheet.write('Y4', '=BDH("' + ticker + ' Equity", "IS_AVG_NUM_SH_FOR_EPS", "FY 2020")')
        worksheet.write('Z4', '=BDH("' + ticker + ' Equity", "PX_LAST", "FY 2020")')
        worksheet.write('AA4', '=BDH("' + ticker + ' Equity", "SHORT_AND_LONG_TERM_DEBT", "FY 2020")')
        worksheet.write('AB4', '=BDH("' + ticker + ' Equity", "CASH_AND_MARKETABLE_SECURITIES", "FY 2020")')
        worksheet.write('AC4', '=BDH("' + ticker + ' Equity", "BS_TOT_ASSET", "FY 2020")')

        worksheet.write('A5', ticker + " 2019")
        worksheet.write('B5', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_1", "FY 2019")')
        worksheet.write('C5', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_2_LOCATION_BASED", "FY 2019")')
        worksheet.write('D5', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_3", "FY 2019")')
        worksheet.write('E5', '=BDH("' + ticker + ' Equity", "SCOPE_3_PURCH_GOODS_SRVCS", "FY 2019")')
        worksheet.write('F5', '=BDH("' + ticker + ' Equity", "SCOPE_3_CAPITAL_GOODS", "FY 2019")')
        worksheet.write('G5', '=BDH("' + ticker + ' Equity", "SCOPE_3_FUEL_ENRG_RELATD_ACT", "FY 2019")')
        worksheet.write('H5', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_TRANS_DIST", "FY 2019")')
        worksheet.write('I5', '=BDH("' + ticker + ' Equity", "SCOPE_3_WASTE_GENRTD_IN_OP", "FY 2019")')
        worksheet.write('J5', '=BDH("' + ticker + ' Equity", "SCOPE_3_BUSINESS_TRVL_EMISSIONS", "FY 2019")')
        worksheet.write('K5', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMPLOYEE_COMMUTING", "FY 2019")')
        worksheet.write('L5', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_LEASED_ASSETS", "FY 2019")')
        worksheet.write('M5', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_TRANS_DIST", "FY 2019")')
        worksheet.write('N5', '=BDH("' + ticker + ' Equity", "SCOPE_3_PRCSS_OF_SOLD_PRODS", "FY 2019")')
        worksheet.write('O5', '=BDH("' + ticker + ' Equity", "SCOPE_3_USE_SOLD_PRODUCTS", "FY 2019")')
        worksheet.write('P5', '=BDH("' + ticker + ' Equity", "SCOPE_3_EOL_TRTMNT_PRODS", "FY 2019")')
        worksheet.write('Q5', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_LEASE_ASSTS", "FY 2019")')
        worksheet.write('R5', '=BDH("' + ticker + ' Equity", "SCOPE_3_FRANCHISES", "FY 2019")')
        worksheet.write('S5', '=BDH("' + ticker + ' Equity", "SCOPE_3_INVESTMENTS", "FY 2019")')
        worksheet.write('T5', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMISSIONS_OTHER", "FY 2019")')
        worksheet.write('U5', '=BDH("' + ticker + ' Equity", "ENTERPRISE_VALUE", "FY 2019")')
        worksheet.write('V5', '=BDH("' + ticker + ' Equity", "IS_COMP_SALES", "FY 2019")')
        worksheet.write('W5', '=BDH("' + ticker + ' Equity", "HISTORICAL_MARKET_CAP", "FY 2019")')
        worksheet.write('X5', '=BDP("' + ticker + ' Equity", "NAME")')
        worksheet.write('Y5', '=BDH("' + ticker + ' Equity", "IS_AVG_NUM_SH_FOR_EPS", "FY 2019")')
        worksheet.write('Z5', '=BDH("' + ticker + ' Equity", "PX_LAST", "FY 2019")')
        worksheet.write('AA5', '=BDH("' + ticker + ' Equity", "SHORT_AND_LONG_TERM_DEBT", "FY 2019")')
        worksheet.write('AB5', '=BDH("' + ticker + ' Equity", "CASH_AND_MARKETABLE_SECURITIES", "FY 2019")')
        worksheet.write('AC5', '=BDH("' + ticker + ' Equity", "BS_TOT_ASSET", "FY 2019")')

        worksheet.write('A6', ticker + " 2018")
        worksheet.write('B6', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_1", "FY 2018")')
        worksheet.write('C6', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_2_LOCATION_BASED", "FY 2018")')
        worksheet.write('D6', '=BDH("' + ticker + ' Equity", "GHG_SCOPE_3", "FY 2018")')
        worksheet.write('E6', '=BDH("' + ticker + ' Equity", "SCOPE_3_PURCH_GOODS_SRVCS", "FY 2018")')
        worksheet.write('F6', '=BDH("' + ticker + ' Equity", "SCOPE_3_CAPITAL_GOODS", "FY 2018")')
        worksheet.write('G6', '=BDH("' + ticker + ' Equity", "SCOPE_3_FUEL_ENRG_RELATD_ACT", "FY 2018")')
        worksheet.write('H6', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_TRANS_DIST", "FY 2018")')
        worksheet.write('I6', '=BDH("' + ticker + ' Equity", "SCOPE_3_WASTE_GENRTD_IN_OP", "FY 2018")')
        worksheet.write('J6', '=BDH("' + ticker + ' Equity", "SCOPE_3_BUSINESS_TRVL_EMISSIONS", "FY 2018")')
        worksheet.write('K6', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMPLOYEE_COMMUTING", "FY 2018")')
        worksheet.write('L6', '=BDH("' + ticker + ' Equity", "SCOPE_3_UPSTREAM_LEASED_ASSETS", "FY 2018")')
        worksheet.write('M6', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_TRANS_DIST", "FY 2018")')
        worksheet.write('N6', '=BDH("' + ticker + ' Equity", "SCOPE_3_PRCSS_OF_SOLD_PRODS", "FY 2018")')
        worksheet.write('O6', '=BDH("' + ticker + ' Equity", "SCOPE_3_USE_SOLD_PRODUCTS", "FY 2018")')
        worksheet.write('P6', '=BDH("' + ticker + ' Equity", "SCOPE_3_EOL_TRTMNT_PRODS", "FY 2018")')
        worksheet.write('Q6', '=BDH("' + ticker + ' Equity", "SCOPE_3_DWNSTRM_LEASE_ASSTS", "FY 2018")')
        worksheet.write('R6', '=BDH("' + ticker + ' Equity", "SCOPE_3_FRANCHISES", "FY 2018")')
        worksheet.write('S6', '=BDH("' + ticker + ' Equity", "SCOPE_3_INVESTMENTS", "FY 2018")')
        worksheet.write('T6', '=BDH("' + ticker + ' Equity", "SCOPE_3_EMISSIONS_OTHER", "FY 2018")')
        worksheet.write('U6', '=BDH("' + ticker + ' Equity", "ENTERPRISE_VALUE", "FY 2018")')
        worksheet.write('V6', '=BDH("' + ticker + ' Equity", "IS_COMP_SALES", "FY 2018")')
        worksheet.write('W6', '=BDH("' + ticker + ' Equity", "HISTORICAL_MARKET_CAP", "FY 2018")')
        worksheet.write('X6', '=BDP("' + ticker + ' Equity", "NAME")')
        worksheet.write('Y6', '=BDH("' + ticker + ' Equity", "IS_AVG_NUM_SH_FOR_EPS", "FY 2018")')
        worksheet.write('Z6', '=BDH("' + ticker + ' Equity", "PX_LAST", "FY 2018")')
        worksheet.write('AA6', '=BDH("' + ticker + ' Equity", "SHORT_AND_LONG_TERM_DEBT", "FY 2018")')
        worksheet.write('AB6', '=BDH("' + ticker + ' Equity", "CASH_AND_MARKETABLE_SECURITIES", "FY 2018")')
        worksheet.write('AC6', '=BDH("' + ticker + ' Equity", "BS_TOT_ASSET", "FY 2018")')

        print('\nA new .xlsx file containing the Bloomberg plugin functions for your desired company (' + ticker + ') from 2016-2023 has been successfully created!')

        workbook.close()
    except:
        print('\nProcess failed for ' + ticker + '!')


print("\nTask fully completed!!\n\n")